### ISSUE TITLE
Massive slowdowns with new update.

### ISSUE THREAD

**Issue by Matu67** [davidsev/owlbear-aoe2#1]
With the new update it looks like when I draw the AOE with the tool, it's super laggy and choppy for any shape and not at all as smooth as before the update. I am using fog of war.

**Comment by davidsev** [comment]
Hi, thanks for the report.

What settings are you using, and on what type of grid?
Is it always slow, or only with very big AoEs?
Also, what browser are you using.

**Comment by davidsev** [comment]
Hi, sorry I forgot to reply to this, it's been fixed.
